name: Unit Test PR Action

on:
    pull_request:
        types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore npm cache
        uses: actions/cache@v1
        id: node-modules-cache
        env:
          cache-name: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 14.3.0
          registry-url: 'https://npm.pkg.github.com'


      - name: Restore jest cache
        uses: actions/cache@v1
        env:
            cache-name: cache-jest
        with:
            path: ./jest-cache
            key: ${{ runner.os }}-build-${{ env.cache-name }}
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-


      - name: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: yarn prepare
        run: |
          yarn prepare

      - name: Running Validations
        run: yarn test
